build:
  version: "1.0"

login:
  message: "Hello"

jwt:
  secret: ${JWT_SECRET:ycs78G&SACFSIA789sagc}
server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:login
    username: teama
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://eurekaserver:8091/eureka/"
