build:
  version: "3.0"

login:
  message: "Hello default"

jwt:
  secret: ${JWT_SECRET:ycs78G&SACFSIA789sagc}

server:
  port: 8081

spring:
  application:
    name: login
  
  # config:
  #   import: "optional:configserver:http://localhost:8090/" # Config Server URL

  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: rootpassword

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  # h2:
  #   console:
  #     path: /h2-console
  #     enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
